name: Build CARVER Live datafeed

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Build feed from Excel
        env:
          EXCEL_PATH: data/CARVER-Pa-Impact-Assessment-Templat.xlsx  # change if your path differs
          OUTPUT_PATH: public/datafeed.json
          MAX_ASSETS: '12'
        run: |
          python scripts/build_datafeed.py

      - name: Commit feed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add public/datafeed.json
          git commit -m "chore: update datafeed" || echo "No changes"
          git push